[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://taxiapp-production-8559.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
